#!/usr/bin/env python3
"""Render the J.A.R.V.I.S. Ops dashboard from state files.

Writes:
  jarvis-ops/dashboard/DASHBOARD.md   markdown tables (readable on GitHub)
  jarvis-ops/dashboard/dashboard.html the live page published as an Artifact
"""
import json
import subprocess
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

OPS = Path(__file__).resolve().parent.parent
REPO = OPS.parent
DASH = OPS / "dashboard"
AGENTS = ("academic-core", "ledger-fi", "social-ops", "hustle-engine")
OPEN = ("plan", "verify", "execute", "blocked")


def read_json(path, default):
    try:
        return json.loads(path.read_text())
    except (FileNotFoundError, json.JSONDecodeError):
        return default


def next_cycle(config, now):
    tz = ZoneInfo(config["timezone"])
    local = now.astimezone(tz)
    for day in range(2):
        for c in sorted(config["cycles"], key=lambda c: c["local_time"]):
            h, m = map(int, c["local_time"].split(":"))
            t = (local + timedelta(days=day)).replace(hour=h, minute=m, second=0, microsecond=0)
            if t > local:
                return {"name": c["name"], "at": t.isoformat()}
    return None


def recent_runs(limit=8):
    path = OPS / "logs" / "runs.jsonl"
    if not path.exists():
        return []
    rows = [json.loads(l) for l in path.read_text().splitlines() if l.strip()]
    return rows[-limit:][::-1]


def recent_commits(limit=8):
    try:
        out = subprocess.run(
            ["git", "log", f"-{limit}", "--date=iso-strict", "--pretty=format:%h\x1f%ad\x1f%s"],
            cwd=REPO, capture_output=True, text=True, check=True).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []
    return [dict(zip(("sha", "at", "subject"), l.split("\x1f"))) for l in out.splitlines() if l]


def collect():
    config = read_json(OPS / "config.json", {})
    tasks = read_json(OPS / "state" / "tasks.json", {"goals": [], "tasks": []})
    agents = {a: read_json(OPS / "agents" / a / "state.json", {}) for a in AGENTS}
    now = datetime.now(ZoneInfo(config.get("timezone", "UTC")))
    threads = []
    for a in AGENTS:
        s = agents[a]
        mine = [t for t in tasks["tasks"] if t["agent"] == a]
        threads.append({
            "id": a,
            "label": config["agents"][a]["label"],
            "domain": config["agents"][a]["domain"],
            "phase": s.get("phase", "uninit"),
            "pending": sum(t["phase"] in ("plan", "verify", "execute") for t in mine),
            "blocked": sum(t["phase"] == "blocked" for t in mine),
            "done": sum(t["phase"] == "done" for t in mine),
            "last_run": s.get("last_run"),
            "summary": s.get("summary", ""),
            "weight": config["priority_weights"][a],
        })
    alerts = []
    for a in AGENTS:
        for al in agents[a].get("alerts", []):
            alerts.append({**al, "agent": config["agents"][a]["label"]})
    rank = {"critical": 0, "warn": 1, "info": 2}
    alerts.sort(key=lambda x: (rank.get(x.get("level"), 3), x.get("at") or ""))
    open_tasks = [t for t in tasks["tasks"] if t["phase"] in OPEN]
    open_tasks.sort(key=lambda t: (t["priority"], t.get("due") or "9999"))
    return {
        "generated": now.isoformat(timespec="minutes"),
        "system": config.get("system", "J.A.R.V.I.S. Ops"),
        "timezone": config.get("timezone"),
        "next_cycle": next_cycle(config, now),
        "cycles": config.get("cycles", []),
        "autonomy": config.get("autonomy", {}),
        "threads": threads,
        "alerts": alerts,
        "tasks": open_tasks,
        "goals": tasks["goals"],
        "agents": {a: agents[a].get("metrics", {}) for a in AGENTS},
        "runs": recent_runs(),
        "commits": recent_commits(),
    }


def md_escape(s):
    return str(s if s is not None else "—").replace("|", "\\|").replace("\n", " ")


def table(headers, rows):
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(md_escape(c) for c in r) + " |" for r in rows]
    return "\n".join(lines)


def render_md(d):
    nc = d["next_cycle"]
    out = [
        f"# {d['system']} — Dashboard",
        "",
        f"`generated {d['generated']}` · `next cycle: {nc['name']} @ {nc['at']}`" if nc else f"`generated {d['generated']}`",
        "",
        "> Generated by `jarvis-ops/scripts/render_dashboard.py`. Do not edit by hand.",
        "",
        "## Threads",
        "",
        table(["Thread", "Domain", "Phase", "Pending", "Blocked", "Done", "Last run", "Share"],
              [[t["label"], t["domain"], t["phase"], t["pending"], t["blocked"], t["done"],
                t["last_run"], f"{t['weight']}%"] for t in d["threads"]]),
        "",
        "## Alerts",
        "",
        table(["Level", "Agent", "Message", "At"],
              [[a.get("level"), a["agent"], a.get("msg"), a.get("at")] for a in d["alerts"]])
        if d["alerts"] else "_No alerts._",
        "",
        "## Open tasks",
        "",
        table(["ID", "Agent", "Task", "Phase", "P", "Due", "Autonomy"],
              [[t["id"], t["agent"], t["title"], t["phase"], t["priority"], t.get("due"), t["autonomy"]]
               for t in d["tasks"]]) if d["tasks"] else "_No open tasks._",
        "",
        "## Recent cycles",
        "",
        table(["Cycle", "Started", "Result", "Tasks run", "Notes"],
              [[r.get("cycle"), r.get("started"), r.get("result"), r.get("tasks_run"), r.get("notes")]
               for r in d["runs"]]) if d["runs"] else "_No cycles yet._",
        "",
        "## Commits",
        "",
        table(["SHA", "At", "Subject"], [[c["sha"], c["at"], c["subject"]] for c in d["commits"]]),
        "",
    ]
    return "\n".join(out)


def render_html(d):
    template = (DASH / "template.html").read_text()
    blob = json.dumps(d, ensure_ascii=False).replace("</", "<\\/")
    return template.replace("/*__DASHBOARD_DATA__*/null", blob)


def main():
    d = collect()
    (DASH / "DASHBOARD.md").write_text(render_md(d))
    (DASH / "dashboard.html").write_text(render_html(d))
    print("dashboard rendered:", (DASH / "DASHBOARD.md").relative_to(REPO), (DASH / "dashboard.html").relative_to(REPO))


if __name__ == "__main__":
    main()
